### ISSUE TITLE
Shouldn't cage face normal be calculated in real time?

### ISSUE THREAD

**Issue by zhuzihan728** [Naz9898/GreenCoordinatesPython#1]
Hi, I read in ur code cell 3 that the cage face normals are pre computed for later deformation
`n = igl.per_face_normals( v_c, f_c, np.array([1.0, 0, 0]) ) `
Shouldn't those be calculated from the dynamic cage mesh tho?

**Comment by Naz9898** [comment]
Hello, I checked the paper again and you are absolutely right. I fixed the code, thank you!
